# Generated by Django 5.0.4 on 2024-05-09 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_cost', models.PositiveIntegerField(max_length=200)),
                ('drFee', models.PositiveIntegerField()),
                ('total_amount', models.PositiveIntegerField()),
                ('insurance_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HealthEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips', models.CharField(max_length=250)),
                ('resource', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_record', models.CharField(max_length=1500)),
                ('treatment', models.CharField(max_length=2500)),
                ('medicine', models.CharField(max_length=250)),
                ('next_visit', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_age', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('symptoms', models.CharField(max_length=1000)),
                ('assignedDoctorId', models.PositiveIntegerField(null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appiontment', models.DateField(auto_now=True)),
                ('description', models.CharField(max_length=1000)),
                ('patientName', models.CharField(max_length=300)),
                ('doctorName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.doctor')),
            ],
        ),
    ]
