# Generated by Django 5.0.4 on 2024-05-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='address',
            new_name='patient_address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
        migrations.AlterField(
            model_name='billing',
            name='medicine_cost',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.CharField(max_length=200),
        ),
    ]
