# Generated by Django 5.0.4 on 2024-05-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentShedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateField()),
                ('appointment_details', models.CharField(max_length=100)),
                ('patient_info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=50, null=True)),
                ('status', models.BooleanField(default=True)),
                ('department', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='E_Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.CharField(max_length=1500)),
                ('drug', models.CharField(max_length=500)),
                ('pharmacies', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='PatientManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_records', models.CharField(max_length=200)),
                ('medical_history', models.CharField(max_length=100)),
                ('treatment_plans', models.CharField(max_length=500)),
                ('decision_making', models.CharField(max_length=200)),
            ],
        ),
    ]
